// Generated by design-system/scripts/generate-platform-tokens.mjs
// source-version: 1.2.0
package com.dflh.designsystem

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object DesignTokens {
    val accentPill = Color(0xFF1A1A2E)
    val accentPillForeground = Color(0xFFFDFBF4)
    val avatar1 = Color(0xFF7C3AED)
    val avatar2 = Color(0xFFEA7316)
    val avatar3 = Color(0xFF0D9488)
    val avatar4 = Color(0xFFBE185D)
    val avatar5 = Color(0xFF8B5CF6)
    val background = Color(0xFFF5F4F0)
    val black = Color(0xFF000000)
    val border = Color(0xFFE8E5DF)
    val borderHover = Color(0xFFC8C5BF)
    val borderSubtle = Color(0xFFF0EDE8)
    val catNoticeBg = Color(0xFFE8E5DF)
    val catNoticeBorder = Color(0xFFC8C5BF)
    val catNoticeText = Color(0xFF1A1A2E)
    val disabled = Color(0xFFCFCBD7)
    val donationTreeFlowerHighlight = Color(0xFFFFD3E0)
    val donationTreeFlowerMid = Color(0xFFFF8FAE)
    val donationTreeFlowerShadow = Color(0xFFE8688F)
    val donationTreeFruitHighlight = Color(0xFFFFB177)
    val donationTreeFruitMid = Color(0xFFFF7A3D)
    val donationTreeFruitShadow = Color(0xFFE85D1F)
    val donationTreeFruitStem = Color(0xFF4A7A2E)
    val donationTreeLeafHighlight = Color(0xFFB8E68C)
    val donationTreeLeafMid = Color(0xFF7CBB4E)
    val donationTreeLeafShadow = Color(0xFF5C9438)
    val donationTreePotBase = Color(0xFFC97239)
    val donationTreePotHighlight = Color(0xFFF0AD7A)
    val donationTreePotShadow = Color(0xFFA85A2C)
    val donationTreeRimHighlight = Color(0xFFF7C295)
    val donationTreeRimShadow = Color(0xFFE8955F)
    val donationTreeSeedHighlight = Color(0xFFF0E4C8)
    val donationTreeSeedMid = Color(0xFFD9C49A)
    val donationTreeSeedShadow = Color(0xFFB8A177)
    val donationTreeSoilCenter = Color(0xFF5C4530)
    val donationTreeSoilEdge = Color(0xFF3D2E1F)
    val donationTreeSproutHighlight = Color(0xFF8BC96B)
    val donationTreeSproutShadow = Color(0xFF6BA34A)
    val donationTreeTrunkHighlight = Color(0xFF9C6B45)
    val donationTreeTrunkShadow = Color(0xFF6B4226)
    val error = Color(0xFFEF4444)
    val errorBorder = Color(0xFFFECACA)
    val errorLight = Color(0xFFFEF2F2)
    val errorSubtle = Color(0xFFFEF2F2)
    val errorText = Color(0xFFDC2626)
    val heroFrom = Color(0xFF0F1B35)
    val heroTo = Color(0xFF1E3A6E)
    val heroVia = Color(0xFF1A2F5A)
    val kakao = Color(0xFFFEE500)
    val kakaoText = Color(0xFF191919)
    val navIconSelected = Color(0xFFFBBF6A)
    val primary = Color(0xFF1A1A2E)
    val primaryHover = Color(0xFF0F1B35)
    val primaryLight = Color(0xFFE8E5DF)
    val primaryMuted = Color(0xFFC8C5BF)
    val read = Color(0xFF94A3B8)
    val success = Color(0xFF10B981)
    val successSubtle = Color(0xFFECFDF5)
    val successText = Color(0xFF047857)
    val surface = Color(0xFFFAFAF8)
    val surfaceElevated = Color(0xFFFDFBF4)
    val textPlaceholder = Color(0xFFAAAAAA)
    val textPrimary = Color(0xFF1A1A2E)
    val textSecondary = Color(0xFF555555)
    val textTertiary = Color(0xFF888888)
    val warm = Color(0xFFF59E0B)
    val warmLight = Color(0xFFFFFBEB)
    val warningSubtle = Color(0xFFFFFBEB)
    val warningText = Color(0xFF92400E)
    val white = Color(0xFFFFFFFF)

    object Spacing {
        val s0 = 0.dp
        val s1 = 4.dp
        val s10 = 40.dp
        val s2 = 8.dp
        val s3 = 12.dp
        val s4 = 16.dp
        val s5 = 20.dp
        val s6 = 24.dp
        val s7 = 28.dp
        val s8 = 32.dp
        val s9 = 36.dp
    }

    object Radius {
        val full = 9999.dp
        val lg = 16.dp
        val md = 12.dp
        val sm = 8.dp
        val xl = 20.dp
        val xxl = 24.dp
    }

    object Layout {
        val cardGap = 12.dp
        val containerMaxWidth = 1080.dp
        val feedPostCardRadius = 18.dp
        val feedPostDetailSectionSpacing = 10.dp
        val feedPostDetailSpacing = 16.dp
        val messageBubbleMaxWidthRatio = 0.76f
        val profileHorizontalPadding = 2.dp
        val screenPadMobile = 16.dp
        val screenPadTablet = 24.dp
    }

    object Sizing {
        val feedCardThumbnailHeightMax = 168.dp
        val feedCardThumbnailHeightMin = 152.dp
        val feedHeroHeightMax = 190.dp
        val feedHeroHeightMin = 170.dp
        val headerHeightIos = 52.dp
        val headerHeightWeb = 56.dp
        val loadingStateMaxWidth = 260.dp
        val messageComposerHeight = 64.dp
        val messageUnreadBadge = 24.dp
        val safeBottomNavHeight = 56.dp
        val touchTarget = 44.dp
    }

    object Typography {
        val body = 16.sp
        val bodySm = 15.sp
        val bodyXs = 13.sp
        val caption = 11.sp
        val display = 36.sp
        val h1 = 30.sp
        val h2 = 24.sp
        val h3 = 20.sp
        val mini = 10.sp
        val title = 18.sp
        const val fontWeightBold = 700
        const val fontWeightMedium = 500
        const val fontWeightRegular = 400
        const val fontWeightSemibold = 600
    }

    object Iconography {
        val sizeLg = 18.dp
        val sizeMd = 16.dp
        val sizeSm = 14.dp
        val sizeXl = 20.dp
        val sizeXs = 12.dp
        val sizeXxl = 24.dp
        const val lineWeightLight = 1
        const val lineWeightMedium = 2.5
        const val lineWeightRegular = 2
    }

    object Elevation {
        const val card = "0 1px 3px 0 rgba(0,0,0,0.04), 0 1px 2px -1px rgba(0,0,0,0.02)"
        const val cardHover = "0 8px 25px -5px rgba(0,0,0,0.08), 0 4px 10px -3px rgba(0,0,0,0.03)"
        const val float = "0 8px 30px rgba(0,0,0,0.08)"
        const val nav = "0 4px 24px 0 rgba(0,0,0,0.06)"
        const val primaryGlow = "0 4px 14px 0 rgba(26,26,46,0.25)"
        const val xs = "0 1px 2px 0 rgba(0,0,0,0.03)"
    }

    object Opacity {
        const val deep = 0.35
        const val divider = 0.45
        const val donationTreeGloss = 0.3
        const val donationTreeGroundShadow = 0.12
        const val faint = 0.2
        const val low = 0.15
        const val mutedIcon = 0.6
        const val overlay = 0.08
        const val raised = 0.18
        const val shadow = 0.07
        const val strongIcon = 0.65
        const val subtle = 0.14
        const val surfaceAlt = 0.85
        const val surfaceSoft = 0.75
        const val surfaceSoftStrong = 0.76
        const val surfaceSubtle = 0.72
        const val textEmphasis = 0.92
        const val titleEmphasis = 0.9
    }

    object AnimationMs {
        const val baseMs = 250L
        const val defaultMs = 400L
        const val quickMs = 150L
        const val slowMs = 550L
        const val easingSmooth = "cubic-bezier(0.16,1,0.3,1)"
        const val easingStandard = "ease-out"
    }
}
