// Generated by design-system/scripts/generate-platform-tokens.mjs
// source-version: 1.10.0
import Foundation
import SwiftUI
import UIKit

public enum DSPalette {
  public enum Light {
    public static let brandAccent = Color(hex: "#F59E0B")
    public static let brandAccentBorder = Color(hex: "#FDE7B6")
    public static let brandAccentSubtle = Color(hex: "#FFFBEB")
    public static let brandAccentText = Color(hex: "#B45309")
    public static let brandOnAccent = Color(hex: "#1A1A2E")
    public static let brandOnPrimary = Color(hex: "#FDFBF4")
    public static let brandPrimary = Color(hex: "#1A1A2E")
    public static let canvas = Color(hex: "#F5F4F0")
    public static let danger = Color(hex: "#DC2626")
    public static let ink1 = Color(hex: "#1A1A2E")
    public static let ink2 = Color(hex: "#555555")
    public static let ink3 = Color(hex: "#888888")
    public static let ink4 = Color(hex: "#AAAAAA")
    public static let line = Color(hex: "#E8E5DF")
    public static let lineSoft = Color(hex: "#F0EDE8")
    public static let paper = Color(hex: "#FFFFFF")
    public static let paperAlt = Color(hex: "#FAFAF8")
    public static let positive = Color(hex: "#047857")
  }
  public enum Dark {
    public static let brandAccent = Color(hex: "#FBBF6A")
    public static let brandAccentBorder = Color(hex: "#3D3320")
    public static let brandAccentSubtle = Color(hex: "#2A2419")
    public static let brandAccentText = Color(hex: "#FBBF6A")
    public static let brandOnAccent = Color(hex: "#14141C")
    public static let brandOnPrimary = Color(hex: "#14141C")
    public static let brandPrimary = Color(hex: "#F5F4F0")
    public static let canvas = Color(hex: "#14141C")
    public static let danger = Color(hex: "#F87171")
    public static let ink1 = Color(hex: "#F5F4F0")
    public static let ink2 = Color(hex: "#B8B8C2")
    public static let ink3 = Color(hex: "#8A8A96")
    public static let ink4 = Color(hex: "#6E6E7A")
    public static let line = Color(hex: "#33333F")
    public static let lineSoft = Color(hex: "#2A2C35")
    public static let paper = Color(hex: "#1E1E2A")
    public static let paperAlt = Color(hex: "#262636")
    public static let positive = Color(hex: "#34D399")
  }
}

public enum DSColor {
  public static let accentPill = Color(lightHex: "#1A1A2E", darkHex: "#FBBF6A")
  public static let accentPillForeground = Color(lightHex: "#FDFBF4", darkHex: "#14141C")
  public static let avatar1 = Color(hex: "#7C3AED")
  public static let avatar2 = Color(hex: "#EA7316")
  public static let avatar3 = Color(hex: "#0D9488")
  public static let avatar4 = Color(hex: "#BE185D")
  public static let avatar5 = Color(hex: "#8B5CF6")
  public static let background = Color(lightHex: "#F5F4F0", darkHex: "#14141C")
  public static let black = Color(hex: "#000000")
  public static let border = Color(lightHex: "#E8E5DF", darkHex: "#33333F")
  public static let borderHover = Color(hex: "#C8C5BF")
  public static let borderSubtle = Color(lightHex: "#F0EDE8", darkHex: "#2A2C35")
  public static let bubbleMine = Color(lightHex: "#1A1A2E", darkHex: "#F5F4F0")
  public static let bubbleMineText = Color(lightHex: "#FDFBF4", darkHex: "#14141C")
  public static let bubbleTheirs = Color(lightHex: "#FFFFFF", darkHex: "#1E1E2A")
  public static let bubbleTheirsBorder = Color(lightHex: "#E8E5DF", darkHex: "#33333F")
  public static let catNoticeBg = Color(hex: "#E8E5DF")
  public static let catNoticeBorder = Color(hex: "#C8C5BF")
  public static let catNoticeText = Color(hex: "#1A1A2E")
  public static let cautionBorder = Color(lightHex: "#F3C66B", darkHex: "#3D3320")
  public static let cautionSurface = Color(lightHex: "#FFFBEB", darkHex: "#2A2419")
  public static let checkboxCheckedFill = Color(lightHex: "#1A1A2E", darkHex: "#F5F4F0")
  public static let checkboxCheckmark = Color(lightHex: "#FDFBF4", darkHex: "#14141C")
  public static let checkboxDisabled = Color(lightHex: "#AAAAAA", darkHex: "#6E6E7A")
  public static let checkboxUncheckedBorder = Color(lightHex: "#555555", darkHex: "#B8B8C2")
  public static let chipAccentBg = Color(lightHex: "#FFFBEB", darkHex: "#2A2419")
  public static let chipAccentText = Color(lightHex: "#B45309", darkHex: "#FBBF6A")
  public static let chipOutlineBorder = Color(lightHex: "#E8E5DF", darkHex: "#33333F")
  public static let destructiveText = Color(lightHex: "#DC2626", darkHex: "#F87171")
  public static let disabled = Color(hex: "#CFCBD7")
  public static let donationTreeFlowerHighlight = Color(hex: "#FFD3E0")
  public static let donationTreeFlowerMid = Color(hex: "#FF8FAE")
  public static let donationTreeFlowerShadow = Color(hex: "#E8688F")
  public static let donationTreeFruitHighlight = Color(hex: "#FFB177")
  public static let donationTreeFruitMid = Color(hex: "#FF7A3D")
  public static let donationTreeFruitShadow = Color(hex: "#E85D1F")
  public static let donationTreeFruitStem = Color(hex: "#4A7A2E")
  public static let donationTreeLeafHighlight = Color(hex: "#B8E68C")
  public static let donationTreeLeafMid = Color(hex: "#7CBB4E")
  public static let donationTreeLeafShadow = Color(hex: "#5C9438")
  public static let donationTreePotBase = Color(hex: "#C97239")
  public static let donationTreePotHighlight = Color(hex: "#F0AD7A")
  public static let donationTreePotShadow = Color(hex: "#A85A2C")
  public static let donationTreeRimHighlight = Color(hex: "#F7C295")
  public static let donationTreeRimShadow = Color(hex: "#E8955F")
  public static let donationTreeSeedHighlight = Color(hex: "#F0E4C8")
  public static let donationTreeSeedMid = Color(hex: "#D9C49A")
  public static let donationTreeSeedShadow = Color(hex: "#B8A177")
  public static let donationTreeSoilCenter = Color(hex: "#5C4530")
  public static let donationTreeSoilEdge = Color(hex: "#3D2E1F")
  public static let donationTreeSproutHighlight = Color(hex: "#8BC96B")
  public static let donationTreeSproutShadow = Color(hex: "#6BA34A")
  public static let donationTreeTrunkHighlight = Color(hex: "#9C6B45")
  public static let donationTreeTrunkShadow = Color(hex: "#6B4226")
  public static let error = Color(hex: "#EF4444")
  public static let errorBorder = Color(hex: "#FECACA")
  public static let errorLight = Color(hex: "#FEF2F2")
  public static let errorSubtle = Color(hex: "#FEF2F2")
  public static let errorText = Color(hex: "#DC2626")
  public static let fabBackground = Color(lightHex: "#F59E0B", darkHex: "#FBBF6A")
  public static let fabForeground = Color(lightHex: "#1A1A2E", darkHex: "#14141C")
  public static let feedFocusHighlight = Color(lightHex: "#FFFBEB", darkHex: "#2A2419")
  public static let feedLiked = Color(hex: "#C0492F")
  public static let feedWarning = Color(hex: "#8A6A24")
  public static let feedWarningOnDark = Color(hex: "#F5D9A8")
  public static let headerIcon = Color(lightHex: "#1A1A2E", darkHex: "#F5F4F0")
  public static let headerTitle = Color(lightHex: "#1A1A2E", darkHex: "#F5F4F0")
  public static let heroFrom = Color(hex: "#0F1B35")
  public static let heroTo = Color(hex: "#1E3A6E")
  public static let heroVia = Color(hex: "#1A2F5A")
  public static let kakao = Color(hex: "#FEE500")
  public static let kakaoText = Color(hex: "#191919")
  public static let likeActive = Color(lightHex: "#B45309", darkHex: "#FBBF6A")
  public static let likeOnDark = Color(hex: "#FF6B8A")
  public static let mobileFlowBackground = Color(hex: "#F5F4F1")
  public static let mobileFlowBadge = Color(hex: "#EDEAE3")
  public static let mobileFlowPrimary = Color(hex: "#1B1A30")
  public static let mobileFlowWarning = Color(hex: "#B45309")
  public static let mobileFlowWarningSubtle = Color(hex: "#FDF6EC")
  public static let mobileLoginHero = Color(hex: "#172849")
  public static let navIconSelected = Color(lightHex: "#FBBF6A", darkHex: "#FBBF6A")
  public static let outline = Color(lightHex: "#79747E", darkHex: "#938F99")
  public static let primary = Color(hex: "#1A1A2E")
  public static let primaryButtonBg = Color(lightHex: "#1A1A2E", darkHex: "#F5F4F0")
  public static let primaryButtonText = Color(lightHex: "#FDFBF4", darkHex: "#14141C")
  public static let primaryHover = Color(hex: "#0F1B35")
  public static let primaryLight = Color(hex: "#E8E5DF")
  public static let primaryMuted = Color(hex: "#C8C5BF")
  public static let progressFill = Color(lightHex: "#F59E0B", darkHex: "#FBBF6A")
  public static let progressTrack = Color(lightHex: "#F0EDE8", darkHex: "#2A2C35")
  public static let read = Color(hex: "#94A3B8")
  public static let rejectionBorder = Color(lightHex: "#FECACA", darkHex: "#7F1D1D")
  public static let rowDivider = Color(lightHex: "#F0EDE8", darkHex: "#2A2C35")
  public static let rowSurface = Color(lightHex: "#FFFFFF", darkHex: "#1E1E2A")
  public static let secondaryButtonBorder = Color(lightHex: "#E8E5DF", darkHex: "#33333F")
  public static let sectionGap = Color(lightHex: "#F5F4F0", darkHex: "#14141C")
  public static let skeletonFill = Color(lightHex: "#F0EDE8", darkHex: "#2A2C35")
  public static let stateIcon = Color(lightHex: "#767676", darkHex: "#8A8A96")
  public static let statePullHint = Color(lightHex: "#9A9A9A", darkHex: "#6E6E7A")
  public static let statusRejectedSurface = Color(lightHex: "#FEF2F2", darkHex: "#3A1F26")
  public static let success = Color(hex: "#10B981")
  public static let successSubtle = Color(hex: "#ECFDF5")
  public static let successText = Color(hex: "#047857")
  public static let surface = Color(lightHex: "#FAFAF8", darkHex: "#1E1E2A")
  public static let surfaceElevated = Color(lightHex: "#FDFBF4", darkHex: "#262636")
  public static let tabIdleText = Color(lightHex: "#888888", darkHex: "#8A8A96")
  public static let tabIndicator = Color(lightHex: "#1A1A2E", darkHex: "#F5F4F0")
  public static let tabSelectedText = Color(lightHex: "#1A1A2E", darkHex: "#F5F4F0")
  public static let textPlaceholder = Color(hex: "#AAAAAA")
  public static let textPrimary = Color(lightHex: "#1A1A2E", darkHex: "#F5F4F0")
  public static let textSecondary = Color(lightHex: "#555555", darkHex: "#B8B8C2")
  public static let textTertiary = Color(lightHex: "#888888", darkHex: "#8A8A96")
  public static let unreadBadge = Color(lightHex: "#F59E0B", darkHex: "#FBBF6A")
  public static let unreadBadgeText = Color(lightHex: "#1A1A2E", darkHex: "#14141C")
  public static let validationText = Color(lightHex: "#92400E", darkHex: "#FBBF6A")
  public static let warm = Color(lightHex: "#F59E0B", darkHex: "#FBBF6A")
  public static let warmLight = Color(hex: "#FFFBEB")
  public static let warningSubtle = Color(hex: "#FFFBEB")
  public static let warningText = Color(hex: "#92400E")
  public static let white = Color(hex: "#FFFFFF")
}

public enum DSFont {
  public static let sans = "Noto Sans KR, Instrument Sans, Pretendard Variable, ui-sans-serif, system-ui, -apple-system, sans-serif"
  public static let serif = "Pretendard Variable, Pretendard, Georgia, serif"
  public static let body: CGFloat = 16
  public static let bodySm: CGFloat = 15
  public static let bodyXs: CGFloat = 13
  public static let buttonLabel: CGFloat = 16
  public static let buttonLabelCompact: CGFloat = 13
  public static let buttonLabelRegular: CGFloat = 15
  public static let caption: CGFloat = 11
  public static let captionLg: CGFloat = 12
  public static let cardAction: CGFloat = 13
  public static let chipLabel: CGFloat = 14
  public static let display: CGFloat = 36
  public static let feedMetric: CGFloat = 14
  public static let h1: CGFloat = 30
  public static let h2: CGFloat = 24
  public static let h3: CGFloat = 20
  public static let inlineStatus: CGFloat = 13
  public static let listName: CGFloat = 18
  public static let meta: CGFloat = 13
  public static let metaLg: CGFloat = 14
  public static let mini: CGFloat = 10
  public static let mobileFlowSecondaryAction: CGFloat = 14
  public static let mobileFlowTitle: CGFloat = 22
  public static let mobileLoginHeadline: CGFloat = 26
  public static let mobileReceiptValue: CGFloat = 12.5
  public static let navigationLabel: CGFloat = 12
  public static let stateMessage: CGFloat = 14
  public static let stateTitle: CGFloat = 16
  public static let statusMessage: CGFloat = 18
  public static let statusTitle: CGFloat = 20
  public static let tabTitle: CGFloat = 24
  public static let title: CGFloat = 18
  public static let lineHeightBody: CGFloat = 26
  public static let lineHeightButtonLabel: CGFloat = 24
  public static let lineHeightButtonLabelCompact: CGFloat = 18
  public static let lineHeightButtonLabelRegular: CGFloat = 22
  public static let lineHeightCardAction: CGFloat = 18
  public static let lineHeightChipLabel: CGFloat = 20
  public static let lineHeightInlineStatus: CGFloat = 18
  public static let lineHeightStateMessage: CGFloat = 20
  public static let lineHeightStateTitle: CGFloat = 24
  public static let lineHeightStatusMessage: CGFloat = 28
  public static let lineHeightStatusTitle: CGFloat = 28
  public static let fontWeightBold: Double = 700
  public static let fontWeightMedium: Double = 500
  public static let fontWeightRegular: Double = 400
  public static let fontWeightSemibold: Double = 600
}

public enum DSSpacing {
  public static let s0 = 0
  public static let s1 = 4
  public static let s10 = 40
  public static let s2 = 8
  public static let s3 = 12
  public static let s4 = 16
  public static let s5 = 20
  public static let s6 = 24
  public static let s7 = 28
  public static let s8 = 32
  public static let s9 = 36
}

public enum DSRadius {
  public static let button: CGFloat = 8
  public static let chip: CGFloat = 4
  public static let full: CGFloat = 9999
  public static let lg: CGFloat = 16
  public static let md: CGFloat = 12
  public static let mobileFlow: CGFloat = 14
  public static let section: CGFloat = 0
  public static let sm: CGFloat = 8
  public static let thumb: CGFloat = 4
  public static let xl: CGFloat = 20
  public static let xxl: CGFloat = 24
}

public enum DSOpacity {
  public static let deep: Double = 0.35
  public static let divider: Double = 0.45
  public static let donationTreeGloss: Double = 0.3
  public static let donationTreeGroundShadow: Double = 0.12
  public static let failedBubble: Double = 0.6
  public static let faint: Double = 0.2
  public static let low: Double = 0.15
  public static let mutedIcon: Double = 0.6
  public static let navigationPressed: Double = 0.55
  public static let overlay: Double = 0.08
  public static let raised: Double = 0.18
  public static let shadow: Double = 0.07
  public static let strongIcon: Double = 0.65
  public static let subtle: Double = 0.14
  public static let surfaceAlt: Double = 0.85
  public static let surfaceSoft: Double = 0.75
  public static let surfaceSoftStrong: Double = 0.76
  public static let surfaceSubtle: Double = 0.72
  public static let textEmphasis: Double = 0.92
  public static let titleEmphasis: Double = 0.9
}

public enum DSSizing {
  public static let actionBarHeight: CGFloat = 48
  public static let alumniCardThumbHeight: CGFloat = 60
  public static let alumniCardThumbWidth: CGFloat = 96
  public static let avatarHero: CGFloat = 80
  public static let avatarLg: CGFloat = 48
  public static let avatarMd: CGFloat = 40
  public static let avatarSm: CGFloat = 32
  public static let avatarXl: CGFloat = 64
  public static let bottomTabHeight: CGFloat = 56
  public static let chipHeight: CGFloat = 20
  public static let composeMessageMinHeight: CGFloat = 220
  public static let fab: CGFloat = 56
  public static let feedActionInset: CGFloat = 6
  public static let feedBodyLineHeight: CGFloat = 27
  public static let feedCardPadding: CGFloat = 18
  public static let feedCardThumbnailHeightMax: CGFloat = 168
  public static let feedCardThumbnailHeightMin: CGFloat = 152
  public static let feedEngagementGroupGap: CGFloat = 20
  public static let feedEngagementIcon: CGFloat = 21
  public static let feedEngagementInnerGap: CGFloat = 7
  public static let feedEngagementTouchTarget: CGFloat = 48
  public static let feedHeroHeightMax: CGFloat = 190
  public static let feedHeroHeightMin: CGFloat = 170
  public static let feedPendingDot: CGFloat = 6
  public static let filterRowHeight: CGFloat = 44
  public static let floatingNavBorderWidth: CGFloat = 0.5
  public static let floatingNavHeight: CGFloat = 68
  public static let floatingNavIconTop: CGFloat = 14
  public static let floatingNavIndicatorHeight: CGFloat = 3
  public static let floatingNavIndicatorTop: CGFloat = 6
  public static let floatingNavIndicatorWidth: CGFloat = 24
  public static let floatingNavLabelTop: CGFloat = 38
  public static let fullScreenLoader: CGFloat = 72
  public static let headerHeightIos: CGFloat = 52
  public static let headerHeightWeb: CGFloat = 56
  public static let listRowVerticalPad: CGFloat = 16
  public static let loadingStateMaxWidth: CGFloat = 260
  public static let messageComposerHeight: CGFloat = 64
  public static let messageDetailMinHeight: CGFloat = 80
  public static let messageRowHeight: CGFloat = 90
  public static let messageRowVerticalPad: CGFloat = 14
  public static let messageUnreadBadge: CGFloat = 24
  public static let mobileDonationCardHeight: CGFloat = 283
  public static let mobileDonationSummaryHeight: CGFloat = 155
  public static let mobileDonationTreeHeight: CGFloat = 150
  public static let mobileFeedCardHeight: CGFloat = 174
  public static let mobileFeedHeroHeight: CGFloat = 218
  public static let mobileInputHeight: CGFloat = 48
  public static let mobileLoginEmblemSize: CGFloat = 88
  public static let mobileLoginHeroHeight: CGFloat = 305
  public static let primaryButtonHeight: CGFloat = 52
  public static let safeBottomNavHeight: CGFloat = 56
  public static let secondaryButtonHeight: CGFloat = 44
  public static let segmentedTabHeight: CGFloat = 48
  public static let segmentedTabIndicator: CGFloat = 2
  public static let signupPhoto: CGFloat = 140
  public static let stepActionHeight: CGFloat = 52
  public static let stepCardGap: CGFloat = 10
  public static let stepCompletedHeight: CGFloat = 52
  public static let stepInputHeight: CGFloat = 56
  public static let tabHeaderHeight: CGFloat = 56
  public static let tagChipHeight: CGFloat = 24
  public static let touchTarget: CGFloat = 44
  public static let webFeedHeroMinHeight: CGFloat = 260
  public static let webLandingHeroDesktopMinHeight: CGFloat = 520
  public static let webLandingHeroMinHeight: CGFloat = 360
}

public enum DSAnimation {
  public static let base: Double = 0.25 // seconds
  public static let `default`: Double = 0.4 // seconds
  public static let navigationIndicator: Double = 0.16 // seconds
  public static let navigationPress: Double = 0.07 // seconds
  public static let navigationReducedRelease: Double = 0.12 // seconds
  public static let navigationRelease: Double = 0.22 // seconds
  public static let quick: Double = 0.15 // seconds
  public static let slow: Double = 0.55 // seconds
  public static let stepReduced: Double = 0.08 // seconds
  public static let stepTransition: Double = 0.16 // seconds
  public static let easingSmooth = "cubic-bezier(0.16,1,0.3,1)" // easing
  public static let easingStandard = "ease-out" // easing
}

public struct DSElevationValue {
  public let color: Color
  public let opacity: Double
  public let radius: CGFloat
  public let x: CGFloat
  public let y: CGFloat
}

public enum DSElevation {
  public static let cardRaw = "0 1px 3px 0 rgba(0,0,0,0.04), 0 1px 2px -1px rgba(0,0,0,0.02)"
  public static let card = DSElevationValue(color: Color(hex: "#000000"), opacity: 0.04, radius: 3, x: 0, y: 1)
  public static let card2 = DSElevationValue(color: Color(hex: "#000000"), opacity: 0.02, radius: 2, x: 0, y: 1)
  public static let cardHoverRaw = "0 8px 25px -5px rgba(0,0,0,0.08), 0 4px 10px -3px rgba(0,0,0,0.03)"
  public static let cardHover = DSElevationValue(color: Color(hex: "#000000"), opacity: 0.08, radius: 25, x: 0, y: 8)
  public static let cardHover2 = DSElevationValue(color: Color(hex: "#000000"), opacity: 0.03, radius: 10, x: 0, y: 4)
  public static let floatRaw = "0 8px 30px rgba(0,0,0,0.08)"
  public static let float = DSElevationValue(color: Color(hex: "#000000"), opacity: 0.08, radius: 30, x: 0, y: 8)
  public static let navRaw = "0 4px 24px 0 rgba(0,0,0,0.06)"
  public static let nav = DSElevationValue(color: Color(hex: "#000000"), opacity: 0.06, radius: 24, x: 0, y: 4)
  public static let primaryGlowRaw = "0 4px 14px 0 rgba(26,26,46,0.25)"
  public static let primaryGlow = DSElevationValue(color: Color(hex: "#1A1A2E"), opacity: 0.25, radius: 14, x: 0, y: 4)
  public static let xsRaw = "0 1px 2px 0 rgba(0,0,0,0.03)"
  public static let xs = DSElevationValue(color: Color(hex: "#000000"), opacity: 0.03, radius: 2, x: 0, y: 1)
}

public enum DSLayout {
  public static let adaptiveDetailMin: CGFloat = 360
  public static let adaptiveForm: CGFloat = 480
  public static let adaptiveFormLarge: CGFloat = 520
  public static let adaptiveLandscapeHeightRatio: CGFloat = 0.7142857143
  public static let adaptiveLargeWidth: CGFloat = 840
  public static let adaptiveListMax: CGFloat = 360
  public static let adaptiveListMin: CGFloat = 300
  public static let adaptiveListRatio: CGFloat = 0.42
  public static let adaptiveRailCompact: CGFloat = 78
  public static let adaptiveRailLarge: CGFloat = 96
  public static let adaptiveReadable: CGFloat = 560
  public static let adaptiveReadableLarge: CGFloat = 620
  public static let adaptiveRectangleWidth: CGFloat = 600
  public static let adaptiveShortHeight: CGFloat = 520
  public static let cardGap: CGFloat = 12
  public static let containerMaxWidth: CGFloat = 1080
  public static let feedPostCardRadius: CGFloat = 18
  public static let feedPostDetailSectionSpacing: CGFloat = 10
  public static let feedPostDetailSpacing: CGFloat = 16
  public static let messageBubbleMaxWidthRatio: CGFloat = 0.76
  public static let navigationMotionEasingX1: CGFloat = 0.25
  public static let navigationMotionEasingX2: CGFloat = 0.3
  public static let navigationMotionEasingY1: CGFloat = 1
  public static let navigationMotionEasingY2: CGFloat = 1
  public static let navigationMotionPressedScale: CGFloat = 0.94
  public static let profileHorizontalPadding: CGFloat = 2
  public static let screenPadMobile: CGFloat = 20
  public static let screenPadTablet: CGFloat = 24
  public static let sectionGap: CGFloat = 8
  public static let webMessageBubbleMaxWidthRatio: CGFloat = 0.75
  public static let webModalMaxHeightRatio: CGFloat = 0.85
}

public enum DSIconography {
  public static let sizeLg: CGFloat = 18
  public static let sizeMd: CGFloat = 16
  public static let sizeSm: CGFloat = 14
  public static let sizeState: CGFloat = 40
  public static let sizeStatusGlyph: CGFloat = 36
  public static let sizeXl: CGFloat = 20
  public static let sizeXs: CGFloat = 12
  public static let sizeXxl: CGFloat = 24
  public static let lineWeightLight: Double = 1
  public static let lineWeightMedium: Double = 2.5
  public static let lineWeightRegular: Double = 2
}

extension Color {
    public init(lightHex: String, darkHex: String) {
        let lightComponents = DSColorComponents(hex: lightHex)
        let darkComponents = DSColorComponents(hex: darkHex)
        self.init(uiColor: UIColor { traitCollection in
            let components = traitCollection.userInterfaceStyle == .dark ? darkComponents : lightComponents
            return UIColor(red: components.red, green: components.green, blue: components.blue, alpha: components.alpha)
        })
    }

    public init(hex: String) {
        let components = DSColorComponents(hex: hex)
        self.init(red: components.red, green: components.green, blue: components.blue, opacity: components.alpha)
    }
}

private struct DSColorComponents {
    let red: Double
    let green: Double
    let blue: Double
    let alpha: Double

    init(hex: String) {
        let normalizedHex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var value: UInt64 = 0
        Scanner(string: normalizedHex).scanHexInt64(&value)
        let alphaByte = (value >> 24) & 0xff
        red = Double((value >> 16) & 0xff) / 255
        green = Double((value >> 8) & 0xff) / 255
        blue = Double(value & 0xff) / 255
        alpha = alphaByte == 0 ? 1 : Double(alphaByte) / 255
    }
}

