// Generated by design-system/scripts/generate-platform-tokens.mjs
// source-version: 1.2.0
import Foundation
import SwiftUI
import UIKit

public enum DSColor {
  public static let accentPill = Color(lightHex: "#1A1A2E", darkHex: "#FBBF6A")
  public static let accentPillForeground = Color(lightHex: "#FDFBF4", darkHex: "#14141C")
  public static let avatar1 = Color(hex: "#7C3AED")
  public static let avatar2 = Color(hex: "#EA7316")
  public static let avatar3 = Color(hex: "#0D9488")
  public static let avatar4 = Color(hex: "#BE185D")
  public static let avatar5 = Color(hex: "#8B5CF6")
  public static let background = Color(lightHex: "#F5F4F0", darkHex: "#14141C")
  public static let black = Color(hex: "#000000")
  public static let border = Color(lightHex: "#E8E5DF", darkHex: "#33333F")
  public static let borderHover = Color(hex: "#C8C5BF")
  public static let borderSubtle = Color(hex: "#F0EDE8")
  public static let catNoticeBg = Color(hex: "#E8E5DF")
  public static let catNoticeBorder = Color(hex: "#C8C5BF")
  public static let catNoticeText = Color(hex: "#1A1A2E")
  public static let disabled = Color(hex: "#CFCBD7")
  public static let donationTreeFlowerHighlight = Color(hex: "#FFD3E0")
  public static let donationTreeFlowerMid = Color(hex: "#FF8FAE")
  public static let donationTreeFlowerShadow = Color(hex: "#E8688F")
  public static let donationTreeFruitHighlight = Color(hex: "#FFB177")
  public static let donationTreeFruitMid = Color(hex: "#FF7A3D")
  public static let donationTreeFruitShadow = Color(hex: "#E85D1F")
  public static let donationTreeFruitStem = Color(hex: "#4A7A2E")
  public static let donationTreeLeafHighlight = Color(hex: "#B8E68C")
  public static let donationTreeLeafMid = Color(hex: "#7CBB4E")
  public static let donationTreeLeafShadow = Color(hex: "#5C9438")
  public static let donationTreePotBase = Color(hex: "#C97239")
  public static let donationTreePotHighlight = Color(hex: "#F0AD7A")
  public static let donationTreePotShadow = Color(hex: "#A85A2C")
  public static let donationTreeRimHighlight = Color(hex: "#F7C295")
  public static let donationTreeRimShadow = Color(hex: "#E8955F")
  public static let donationTreeSeedHighlight = Color(hex: "#F0E4C8")
  public static let donationTreeSeedMid = Color(hex: "#D9C49A")
  public static let donationTreeSeedShadow = Color(hex: "#B8A177")
  public static let donationTreeSoilCenter = Color(hex: "#5C4530")
  public static let donationTreeSoilEdge = Color(hex: "#3D2E1F")
  public static let donationTreeSproutHighlight = Color(hex: "#8BC96B")
  public static let donationTreeSproutShadow = Color(hex: "#6BA34A")
  public static let donationTreeTrunkHighlight = Color(hex: "#9C6B45")
  public static let donationTreeTrunkShadow = Color(hex: "#6B4226")
  public static let error = Color(hex: "#EF4444")
  public static let errorBorder = Color(hex: "#FECACA")
  public static let errorLight = Color(hex: "#FEF2F2")
  public static let errorSubtle = Color(hex: "#FEF2F2")
  public static let errorText = Color(hex: "#DC2626")
  public static let heroFrom = Color(hex: "#0F1B35")
  public static let heroTo = Color(hex: "#1E3A6E")
  public static let heroVia = Color(hex: "#1A2F5A")
  public static let kakao = Color(hex: "#FEE500")
  public static let kakaoText = Color(hex: "#191919")
  public static let navIconSelected = Color(lightHex: "#FBBF6A", darkHex: "#FBBF6A")
  public static let primary = Color(hex: "#1A1A2E")
  public static let primaryHover = Color(hex: "#0F1B35")
  public static let primaryLight = Color(hex: "#E8E5DF")
  public static let primaryMuted = Color(hex: "#C8C5BF")
  public static let read = Color(hex: "#94A3B8")
  public static let success = Color(hex: "#10B981")
  public static let successSubtle = Color(hex: "#ECFDF5")
  public static let successText = Color(hex: "#047857")
  public static let surface = Color(lightHex: "#FAFAF8", darkHex: "#1E1E2A")
  public static let surfaceElevated = Color(lightHex: "#FDFBF4", darkHex: "#262636")
  public static let textPlaceholder = Color(hex: "#AAAAAA")
  public static let textPrimary = Color(lightHex: "#1A1A2E", darkHex: "#F5F4F0")
  public static let textSecondary = Color(lightHex: "#555555", darkHex: "#B8B8C2")
  public static let textTertiary = Color(lightHex: "#888888", darkHex: "#8A8A96")
  public static let warm = Color(lightHex: "#F59E0B", darkHex: "#FBBF6A")
  public static let warmLight = Color(hex: "#FFFBEB")
  public static let warningSubtle = Color(hex: "#FFFBEB")
  public static let warningText = Color(hex: "#92400E")
  public static let white = Color(hex: "#FFFFFF")
}

public enum DSFont {
  public static let sans = "Instrument Sans, Pretendard Variable, ui-sans-serif, system-ui, -apple-system, sans-serif"
  public static let serif = "Pretendard Variable, Pretendard, Georgia, serif"
  public static let body: CGFloat = 16
  public static let bodySm: CGFloat = 15
  public static let bodyXs: CGFloat = 13
  public static let caption: CGFloat = 11
  public static let display: CGFloat = 36
  public static let h1: CGFloat = 30
  public static let h2: CGFloat = 24
  public static let h3: CGFloat = 20
  public static let mini: CGFloat = 10
  public static let title: CGFloat = 18
  public static let fontWeightBold: Double = 700
  public static let fontWeightMedium: Double = 500
  public static let fontWeightRegular: Double = 400
  public static let fontWeightSemibold: Double = 600
}

public enum DSSpacing {
  public static let s0 = 0
  public static let s1 = 4
  public static let s10 = 40
  public static let s2 = 8
  public static let s3 = 12
  public static let s4 = 16
  public static let s5 = 20
  public static let s6 = 24
  public static let s7 = 28
  public static let s8 = 32
  public static let s9 = 36
}

public enum DSRadius {
  public static let full: CGFloat = 9999
  public static let lg: CGFloat = 16
  public static let md: CGFloat = 12
  public static let sm: CGFloat = 8
  public static let xl: CGFloat = 20
  public static let xxl: CGFloat = 24
}

public enum DSOpacity {
  public static let deep: Double = 0.35
  public static let divider: Double = 0.45
  public static let donationTreeGloss: Double = 0.3
  public static let donationTreeGroundShadow: Double = 0.12
  public static let faint: Double = 0.2
  public static let low: Double = 0.15
  public static let mutedIcon: Double = 0.6
  public static let overlay: Double = 0.08
  public static let raised: Double = 0.18
  public static let shadow: Double = 0.07
  public static let strongIcon: Double = 0.65
  public static let subtle: Double = 0.14
  public static let surfaceAlt: Double = 0.85
  public static let surfaceSoft: Double = 0.75
  public static let surfaceSoftStrong: Double = 0.76
  public static let surfaceSubtle: Double = 0.72
  public static let textEmphasis: Double = 0.92
  public static let titleEmphasis: Double = 0.9
}

public enum DSSizing {
  public static let feedCardThumbnailHeightMax: CGFloat = 168
  public static let feedCardThumbnailHeightMin: CGFloat = 152
  public static let feedHeroHeightMax: CGFloat = 190
  public static let feedHeroHeightMin: CGFloat = 170
  public static let headerHeightIos: CGFloat = 52
  public static let headerHeightWeb: CGFloat = 56
  public static let loadingStateMaxWidth: CGFloat = 260
  public static let messageComposerHeight: CGFloat = 64
  public static let messageUnreadBadge: CGFloat = 24
  public static let safeBottomNavHeight: CGFloat = 56
  public static let touchTarget: CGFloat = 44
}

public enum DSAnimation {
  public static let base: Double = 0.25 // seconds
  public static let `default`: Double = 0.4 // seconds
  public static let quick: Double = 0.15 // seconds
  public static let slow: Double = 0.55 // seconds
  public static let easingSmooth = "cubic-bezier(0.16,1,0.3,1)" // easing
  public static let easingStandard = "ease-out" // easing
}

public struct DSElevationValue {
  public let color: Color
  public let opacity: Double
  public let radius: CGFloat
  public let x: CGFloat
  public let y: CGFloat
}

public enum DSElevation {
  public static let cardRaw = "0 1px 3px 0 rgba(0,0,0,0.04), 0 1px 2px -1px rgba(0,0,0,0.02)"
  public static let card = DSElevationValue(color: Color(hex: "#000000"), opacity: 0.04, radius: 3, x: 0, y: 1)
  public static let card2 = DSElevationValue(color: Color(hex: "#000000"), opacity: 0.02, radius: 2, x: 0, y: 1)
  public static let cardHoverRaw = "0 8px 25px -5px rgba(0,0,0,0.08), 0 4px 10px -3px rgba(0,0,0,0.03)"
  public static let cardHover = DSElevationValue(color: Color(hex: "#000000"), opacity: 0.08, radius: 25, x: 0, y: 8)
  public static let cardHover2 = DSElevationValue(color: Color(hex: "#000000"), opacity: 0.03, radius: 10, x: 0, y: 4)
  public static let floatRaw = "0 8px 30px rgba(0,0,0,0.08)"
  public static let float = DSElevationValue(color: Color(hex: "#000000"), opacity: 0.08, radius: 30, x: 0, y: 8)
  public static let navRaw = "0 4px 24px 0 rgba(0,0,0,0.06)"
  public static let nav = DSElevationValue(color: Color(hex: "#000000"), opacity: 0.06, radius: 24, x: 0, y: 4)
  public static let primaryGlowRaw = "0 4px 14px 0 rgba(26,26,46,0.25)"
  public static let primaryGlow = DSElevationValue(color: Color(hex: "#1A1A2E"), opacity: 0.25, radius: 14, x: 0, y: 4)
  public static let xsRaw = "0 1px 2px 0 rgba(0,0,0,0.03)"
  public static let xs = DSElevationValue(color: Color(hex: "#000000"), opacity: 0.03, radius: 2, x: 0, y: 1)
}

public enum DSLayout {
  public static let cardGap: CGFloat = 12
  public static let containerMaxWidth: CGFloat = 1080
  public static let feedPostCardRadius: CGFloat = 18
  public static let feedPostDetailSectionSpacing: CGFloat = 10
  public static let feedPostDetailSpacing: CGFloat = 16
  public static let messageBubbleMaxWidthRatio: CGFloat = 0.76
  public static let profileHorizontalPadding: CGFloat = 2
  public static let screenPadMobile: CGFloat = 16
  public static let screenPadTablet: CGFloat = 24
}

public enum DSIconography {
  public static let sizeLg: CGFloat = 18
  public static let sizeMd: CGFloat = 16
  public static let sizeSm: CGFloat = 14
  public static let sizeXl: CGFloat = 20
  public static let sizeXs: CGFloat = 12
  public static let sizeXxl: CGFloat = 24
  public static let lineWeightLight: Double = 1
  public static let lineWeightMedium: Double = 2.5
  public static let lineWeightRegular: Double = 2
}

extension Color {
    public init(lightHex: String, darkHex: String) {
        let lightComponents = DSColorComponents(hex: lightHex)
        let darkComponents = DSColorComponents(hex: darkHex)
        self.init(uiColor: UIColor { traitCollection in
            let components = traitCollection.userInterfaceStyle == .dark ? darkComponents : lightComponents
            return UIColor(red: components.red, green: components.green, blue: components.blue, alpha: components.alpha)
        })
    }

    public init(hex: String) {
        let components = DSColorComponents(hex: hex)
        self.init(red: components.red, green: components.green, blue: components.blue, opacity: components.alpha)
    }
}

private struct DSColorComponents {
    let red: Double
    let green: Double
    let blue: Double
    let alpha: Double

    init(hex: String) {
        let normalizedHex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var value: UInt64 = 0
        Scanner(string: normalizedHex).scanHexInt64(&value)
        let alphaByte = (value >> 24) & 0xff
        red = Double((value >> 16) & 0xff) / 255
        green = Double((value >> 8) & 0xff) / 255
        blue = Double(value & 0xff) / 255
        alpha = alphaByte == 0 ? 1 : Double(alphaByte) / 255
    }
}

